defaults:
  something: $(suffix)-foo
  dependent: $(something)-suffix
  suffix: chiac
  test: default
  top: $(middle)
  middle: $(bottom)
  bottom: $(top)
  tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
  region_resourceGroup: hcp-underlay-$(region)
  region_eventgrid_namespace: maestro-eventgrid-$(region)
  region_maestro_keyvault: maestro-kv-$(region)
  svc_group: hcp-underlay-$(region)-svc
  aks_name: aro-hcp-aks
  maestro_msi: "maestro-server"
  maestro_helm_chart: "oci://$(global_acr).$(azureContainerRegistry.domainNameSuffix)/helm/server"
overrides:
  fairfax:
    defaults:
  public:
    defaults:
      test: public
    overrides:
      dev:
        defaults:
          test: dev
          region_resourceGroup: aro-hcp-$(region)-$(user)
          region_maestro_keyvault: maestro-kv-$(region)-$(user)
          svc_group: aro-hcp-$(region)-svc-$(user)
          maestro_helm_chart: ../maestro/deploy/helm/server
      int:
        defaults:
          test: int
        overrides:
          uksouth:
            test: uksouth
          taiwan:
            test: $(suffix)